name: interview_demo_application
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  intl: any
  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  provider: ^6.0.5
  encrypt: ^5.0.1
  flutter_slidable: ^3.0.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/google.png